{% set name = "asynctest" %}
{% set version = "0.12.3" %}
{% set sha256 = "bbeb45bb41344d2cbb814b4c89c04f2c568742352736cabf7af6fcbed06f66cc" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: "{{ sha256 }}"

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv "

requirements:
  host:
    - pip
    - python >=3.4
  run:
    - python >=3.4

test:
  imports:
    - asynctest

about:
  home: https://github.com/Martiusweb/asynctest/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.md
  summary: Enhance the standard unittest package with features for testing asyncio libraries
  doc_url: http://asynctest.readthedocs.org
  dev_url: https://github.com/Martiusweb/asynctest/

extra:
  recipe-maintainers:
    - hodgsonw
