{% set name = "asynctest" %}
{% set version = "0.13.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c27862842d15d83e6a34eb0b2866c323880eb3a75e4485b079ea11748fd77fac

build:
  noarch: python
  number: 1
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - setuptools
    - python {{ python_min }}
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - asynctest

about:
  home: https://github.com/Martiusweb/asynctest/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.md
  summary: Enhance the standard unittest package with features for testing asyncio libraries
  doc_url: http://asynctest.readthedocs.org
  dev_url: https://github.com/Martiusweb/asynctest/

extra:
  recipe-maintainers:
    - hodgsonw
    - synapticarbors
